spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9094


#Kafka topic
topic.name: test-topic